import AppearanceImpressionMaturityWhite from './appearanceImpressionMaturityWhite'
import AppearanceImpressionYouthWhite from './appearanceImpressionYouthWhite'

type AppearanceImpressionWhite = AppearanceImpressionYouthWhite | AppearanceImpressionMaturityWhite

export default AppearanceImpressionWhite
