version: 2.1

jobs:
  test_front:
    docker:
      - image: cimg/node:18.12.1
        environment:
          NODE_ENV: test
    
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: install-packages
          command: npm install
      
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      
      - run:
          name: lint
          command: npm run lint:eslint

      - run:
          name: test
          command: npm run test

workflows:
  build_test:
    jobs:
      - test_front:
          filters:
            branches:
              ignore: main
