version: 2.1

executors:
  test_image:
    docker:
      - image: cimg/node:18.12.1
        environment:
          NODE_ENV: test

commands:
  npm_install:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  build_and_test:
    executor: test_image
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - run:
          name: lint
          command: npm run lint:eslint
      - run:
          name: test
          command: npm run test

workflows:
  build_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: main
