import AppearanceImpressionMaturityRed from './appearanceImpressionMaturityRed'
import AppearanceImpressionYouthRed from './appearanceImpressionYouthRed'

type AppearanceImpressionRed = AppearanceImpressionYouthRed | AppearanceImpressionMaturityRed

export default AppearanceImpressionRed
