type TastingSheetUseFormName =
  | 'tastingSheet.name'
  | 'tastingSheet.color'
  | 'tastingSheet.time'
  | 'tastingSheet.appearance.clarity'
  | 'tastingSheet.appearance.brightness'
  | 'tastingSheet.appearance.appearanceColors'
  | 'tastingSheet.appearance.intensity'
  | 'tastingSheet.appearance.consistency'
  | 'tastingSheet.appearance.appearanceImpressions'
  | 'tastingSheet.flavor.flavorFirstImpressions'
  | 'tastingSheet.flavor.flavorFruits'
  | 'tastingSheet.flavor.flavorFlowers'
  | 'tastingSheet.flavor.flavorSpices'
  | 'tastingSheet.flavor.flavorImpressions'
  | 'tastingSheet.taste.attack'
  | 'tastingSheet.taste.sweetness'
  | 'tastingSheet.taste.acidity'
  | 'tastingSheet.taste.astringent'
  | 'tastingSheet.taste.bitterness'
  | 'tastingSheet.taste.balance'
  | 'tastingSheet.taste.alcohol'
  | 'tastingSheet.taste.afterTaste'
  | 'tastingSheet.conclusion.evaluation'
  | 'tastingSheet.conclusion.optimumTemperature'
  | 'tastingSheet.conclusion.glass'
  | 'tastingSheet.conclusion.decantage'
  | 'tastingSheet.conclusion.vintage'
  | 'tastingSheet.conclusion.country'
  | 'tastingSheet.conclusion.grape'

export default TastingSheetUseFormName
