type TastingSheetUseFormName =
  | 'tastingSheet.name'
  | 'tastingSheet.color'
  | 'tastingSheet.time'
  | 'tastingSheet.appearance.clarity'
  | 'tastingSheet.appearance.brightness'
  | 'tastingSheet.appearance.appearanceColor'
  | 'tastingSheet.appearance.intensity'
  | 'tastingSheet.appearance.consistency'
  | 'tastingSheet.appearance.appearanceImpression'
  | 'tastingSheet.flavor.flavorFirstImpression'
  | 'tastingSheet.flavor.flavorFruit'
  | 'tastingSheet.flavor.flavorFlower'
  | 'tastingSheet.flavor.flavorSpice'
  | 'tastingSheet.flavor.flavorImpression'
  | 'tastingSheet.taste.attack'
  | 'tastingSheet.taste.sweetness'
  | 'tastingSheet.taste.acidity'
  | 'tastingSheet.taste.astringent'
  | 'tastingSheet.taste.bitterness'
  | 'tastingSheet.taste.balance'
  | 'tastingSheet.taste.alcohol'
  | 'tastingSheet.taste.afterTaste'
  | 'tastingSheet.conclusion.evaluation'
  | 'tastingSheet.conclusion.optimumTemperature'
  | 'tastingSheet.conclusion.glass'
  | 'tastingSheet.conclusion.decantage'
  | 'tastingSheet.conclusion.vintage'
  | 'tastingSheet.conclusion.country'
  | 'tastingSheet.conclusion.grape'

export default TastingSheetUseFormName
