name: eslint

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Npm install
        run: npm install
      - name: Eslint
        run: npm run lint
